@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title Диаграмма контекстов для интернет-банка и автоматизированной банковской системы

Person(client, "Клиент", "Пользователь банка")
Person(callCenterManager, "Менеджер call-центра", "Специалист по работе с клиентами")
Person(backOfficeManager, "Менеджер бэк-офиса", "Специалист по внутренним процессам банка")

System(abs, "Автоматизированная банковская система", "Система для управления внутренними процессами банка")
System(internetBank, "Интернет-банк", "Система для управления депозитами клиентов через веб-интерфейс")
System(callCenterSystem, "Система call-центра", "Система для обработки заявок менеджерами колл-центра")
System(website, "Сайт", "Портал для взаимодействия с клиентами")

System_Ext(telecomOperator, "Телеком оператор", "Система для доставки SMS-сообщений")
System_Ext(smsGateway, "СМС шлюз", "Система для отправки SMS-сообщений")

Rel(client, internetBank, "Открывает депозит", "HTTP")
Rel(client, website, "Открывает депозит", "HTTP")
Rel(website, callCenterSystem, "Отправляет заявки", "API")
Rel(internetBank, callCenterSystem, "Отправляет заявки", "Kafka")
Rel(internetBank, smsGateway, "Отправляет SMS", "API")
Rel(smsGateway, telecomOperator, "Отправляет SMS", "API")
Rel(abs, callCenterSystem, "Отправляет информацию", "API")
Rel(abs, internetBank, "Отправляет согласованные ставки", "API")
Rel(callCenterManager, callCenterSystem, "Управляет заявками", "HTTP")
Rel(callCenterManager, abs, "Получает информацию", "API")
Rel(backOfficeManager, abs, "Подтверждает условия депозита", "HTTP")
@enduml
